version: '3'
services:
  db:
    image: postgres:15.2-alpine
    ports:
      - '5432:5432'
    volumes:
      - .postgres:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/scripts:/scripts
    environment:
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: secret
    tty: true
    stdin_open: true
    networks:
      - my-network
  api:
    build:
      context: ./api
      dockerfile: containers/development/Dockerfile
    command: /bin/bash -c "mix deps.get && chromedriver & iex -S mix phx.server"
    ports:
      - '3000:3000'
    volumes:
      - ./api:/api
    environment:
      - DOCKER_POSTGRES_HOST=db
      - ERL_AFLAGS=-kernel shell_history enabled
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file: .env
    networks:
      - my-network
  web:
    build:
      context: ./web
      dockerfile: containers/development/Dockerfile
    command: /bin/sh -c "yarn install && yarn dev"
    ports:
      - '8080:8080'
    volumes:
      - ./web:/web
      - /web/node_modules
    networks:
      - my-network
networks:
  my-network:
    external: true
